splitthebill/config/routes.rb
Rails.application.routes.draw do
  # resources :expenses
  resources :trips do 
    resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :home
  #resources :users, only: [:index, :show, :new, :create] # Note, a few are left out, because we use Devise

  devise_for :users

   #Custom route for marking an individual contribution as paid!
   patch 'contributions/:id/mark_paid', to: 'contributions#mark_paid', as: 'mark_contribution_paid'

   #Custom route for marking all contributions for a user as paid!
   patch 'users/:id/pay_all_contributions', to: 'contributions#pay_all_contributions', as: 'pay_all_contributions'

  # Defines the root path route ("/")
  root "home#index"

  get "/terms_of_service", to: "pages#terms", as: :terms_of_service
end

splitthebill/app/views/shared/_footer.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Document</title>
</head>
<body>
    <footer>
    <div class="footerContainer">
        <div class="socialIcons">
            <a href="https://www.facebook.com/osu/" target="_blank"><i class="fa-brands fa-facebook"></i></a>
            <a href="https://www.instagram.com/osuengineering/" target="_blank"><i class="fa-brands fa-instagram"></i></a>
            <a href="https://x.com/OhioState" target="_blank"><i class="fa-brands fa-twitter"></i></a>
            <a href="https://github.com" target="_blank"><i class="fa-brands fa-github"></i></a>
            <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank"><i class="fa-brands fa-youtube"></i></a>
        </div>
        <div class="footerNav">
            <ul><li><a href="<%= root_path %>">Home</a></li>
                <li><a href="<%= trips_path %>">Trips</a></li>
                <% if user_signed_in? %>
                <li><a href="<%= edit_user_registration_path %>">Edit Profile</a></li>
                <% else %>
                <li><a href="<%= new_user_session_path %>">Sign In</a></li>
                <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
                <% end %>
                <li><a href="<%= terms_of_service_path %>" target="_blank">Terms of Service</a></li>
            </ul>
        </div>
        <div class="footerBottom">
        <p>Copyright &copy;2024: Created by Paul's Pals</p>
        </div>
    </div>
</footer>
</body>
</html>

splitthebill/app/views/shared/_navbar.html.erb
<nav class=" navbar navbar-expand-lg nv">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Left-aligned items -->
      <ul class="navbar-nav me-auto">
        <li class="nav-item me-2">
          <a class="btn btn-warning navHead logInButton" href="/home">Home</a>
        </li>
        <li class="nav-item me-2">
          <%= link_to 'Trips', trips_path, class: 'btn btn-warning navHead logInButton' %>
        </li>
      </ul>

      <!-- Centered Title -->
      <h1 class="navbar-brand mx-auto welcome">Split The Bill ™</h1>

      <!-- Right-aligned items -->
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
        <li class="nav-item me-2">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary navHead logInButton' %>
        </li>
        <li class="nav-item me-2">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-warning navHead logInButton', id: 'sign-out-link' %>
        </li>
        <% else %>
        <li class="nav-item me-2">
          <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-warning navHead logInButton', id: 'SignInButton'%>
        </li>
        <li class="nav-item me-2">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-warning navHead logInButton' %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>