splitthebill/config/routes.rb
Rails.application.routes.draw do
  # resources :expenses
  resources :trips do 
    resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :home
  #resources :users, only: [:index, :show, :new, :create] # Note, a few are left out, because we use Devise

  devise_for :users

   #Custom route for marking an individual contribution as paid!
   patch 'contributions/:id/mark_paid', to: 'contributions#mark_paid', as: 'mark_contribution_paid'

   #Custom route for marking all contributions for a user as paid!
   patch 'users/:id/pay_all_contributions', to: 'contributions#pay_all_contributions', as: 'pay_all_contributions'

  # Defines the root path route ("/")
  root "home#index"

  get "/terms_of_service", to: "pages#terms", as: :terms_of_service
end

splitthebill/app/models/trip.rb
class Trip < ApplicationRecord
  has_many :participants
  has_many :users, through: :participants
  has_many :expenses

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

splitthebill/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[ show edit update destroy ]
  def index
    if current_user
      # Only include trips where the current user is a participant
      @trips = Trip.joins(:users).where(users: { id: current_user.id }).distinct
    else
      @trips = []
    end
  
    @user = current_user
    @users = User.all
  end

  # GET /trips/1 or /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
    @users = User.all #We want to display each user in the form!

  end

  # GET /trips/1/edit
  def edit
    @users = User.all
  end


  # POST /trips or /trips.json
  def create
    @trip = Trip.new(trip_params)

    #For the trip to include users through participations, we need to pass user ids
    if @trip.save
      # Add selected users to the trip
      user_ids = params[:trip][:user_ids] || []
      user_ids.each do |user_id|
        @trip.participants.create(user_id: user_id)
      end
      redirect_to @trip
    else
      @users = User.all
      render :new
    end
  end

  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_path, status: :see_other, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.require(:trip).permit(:name, :start_date, :end_date)
    end
end

splitthebill/app/helpers/trips_helper.rb
module TripsHelper
end

splitthebill/app/views/trips/_form.html.erb
<div>
    <div class = "trips logIn">
      <%= form_with(model: trip) do |form| %>
        <% if trip.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

            <ul>
              <% trip.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class = "logInForm">
          <%= form.label :name, style: "display: block" %>
          <%= form.text_field :name, class: "logInField" %>
        </div>

        <div class = "logInForm">
          <%= form.label :start_date, style: "display: block" %>
          <%= form.date_field :start_date, class: "logInField" %>
        </div>

        <div class = "logInForm">
          <%= form.label :end_date, style: "display: block" %>
          <%= form.date_field :end_date, class: "logInField" %>
        </div>

        <h5 class = "mt-3">Participants</h5>
        <div>
          <% @users.each do |user| %>
            <div>
              <div class = "logInForm">
                <%= check_box_tag "trip[user_ids][]", user.id, false, class: "form-check-input", id: "trip_user_ids_#{user.id}" %>
                <%= label_tag "trip_user_ids_#{user.id}", user.name, class: "form-check-label" %>
              </div>
            </div>
          <% end %>
        </div>

        <div>
          <% if @trip.new_record?%>
          <h6 class = "logIn trips mt-3">Have Fun On Your Trip!!!</h6>
            <%= form.submit "Save Trip", class: "btn btn-primary logInButton mt-3"%>
          <%else%>
            <%= form.submit "Update Trip", class: "btn btn-primary logInButton mt-3"%>
          <%end%>
        </div>
      <% end %>
    </div>
</div>

splitthebill/app/views/trips/_trip.html.erb
<div class = "trips logIn">
  <div id="<%= dom_id trip %>">
    <h4 class = "tripsHead"><%= trip.name %></h4>
    <h5 class = "mt-3"> <%=trip.start_date%> - <%=trip.end_date%> </h5>
  </div>
</div>

splitthebill/app/views/trips/edit.html.erb
<div class = "container-fluid">
  <div class = "card col-5 trips logIn mb-5">
    <h4 class = "tripsHead p-3">Editing Trip</h4>

    <%= render "form", trip: @trip %>

    <div>
      <%= link_to "Show Trip", @trip, class: "btn btn-primary logInButton mt-3" %>
    </div>
    <div>
      <%= link_to "Back To Trips", trips_path, class: "btn btn-primary logInButton m-3" %>
    </div>
  </div>
</div>

splitthebill/app/views/trips/index.html.erb
<div class = "container-fluid trips">
<% if current_user %>
  <p>Track Another Adventure: <%= link_to "New Trip", new_trip_path, class: "btn btn-primary newTripButton" %></p>
<div class = "card col-6 mb-5 logIn">
  <h4 class = "p-3"> My Trips!</h4>
  <table class = "m-3 tripsTable">
    <tr>
      <th>Trip Name</th>
      <th>Start State</th>
      <th>End Date </th>
      <th>Participants</th>
    </tr>
    <% @trips.each do |trip| %> 
    <tr>
      <th><%= link_to trip.name, trip_path(trip) %></th>
      <td><%= trip.start_date %></td>
      <td><%= trip.end_date %></td>
      <td>
        <% participants = trip.users.map(&:name).join(", ") %>
        <%= participants %>
      </td>
    </tr>
    <% end%>
  </table>
</div>
<% else  %>
<div class = "tripsNotSign">
  <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary signButton' %>
<p>You are currently not signed in. Please press "Sign In" above to view, create, or show trips and/or expenses. Thank You!</p>
<% end %>
</div>
</div>

splitthebill/app/views/trips/new.html.erb
<div class = "container-fluid">
  <div class = "card col-5 logIn trips mb-5">
    <h4 class = "trips mt-3">New trip</h4>

    <%= render "form", trip: @trip %>

    <br>

    <div class = "p-2 logIn">
      <%= link_to "Back to trips", trips_path, class: "btn btn-primary logInButton mb-3" %>
    </div>
  </div>
</div>

splitthebill/app/views/trips/show.html.erb
<div class = "container-fluid">
  <div class = "card trips logIn col-5">
    <p style="color: green"><%= notice %></p>

    <%= render @trip %>
    <div class = "trips">
      <p class = "tripsHead">
        <h5>Participants</h5>
        <% @trip.participants.each do |participant| %>
            <p><%= participant.user.name %>:
            <%= participant.user.email %></p>
        <% end %>
    </div>
    <div class = "trips">
      <%= link_to "Edit this trip", edit_trip_path(@trip), class: "btn btn-primary logInButton m-2" %>
      <%= link_to "Back to trips", trips_path, class: "btn btn-primary logInButton" %>

      <%= link_to 'View Expenses', trip_expenses_path(@trip), class: "btn btn-primary logInButton m-2" %>

      <%= button_to "Delete Trip", @trip, class: "btn btn-primary logInButton", method: :delete, class: "btn btn-primary logInButton m-2 mb-3" %>
    </div>
  </div>
</div>